# Generated by Django 2.0 on 2019-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='item',
            new_name='name',
        ),
        migrations.AddField(
            model_name='list',
            name='additional',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
